### PR TITLE
add dataProxy parameter

### PR DESCRIPTION
**Pull request by RobertUpchurch**
Allows users to use this plugin when using the prisma data proxy.

### CODE REVIEW

**Review by danieluhm2004 — CHANGES_REQUESTED** [review]
I appreciate your pull request.

But, your pull request is not working when the user disabled the data proxy. I will fix your problem and merge it.

Thank you.

**Comment by danieluhm2004** [comment]
Can you enable "Allow edits from maintainers." please?

**Comment by RobertUpchurch** [comment]
Doesnt seem i can 'allow from maintaners" since i forked it into an Organization. Lame. I invited you with write access to the fork. Hopefully that fixes it or I can refork into a persona github. LMK

**Review by danieluhm2004 — APPROVED** [review]
LGTM!

**Comment by RobertUpchurch** [comment]
Amazing! will watch for NPM release. Thanks

**Pull request merged**
